function plot_node(axes_handle,GlobalNodeList,x,y,z,color)

for A = GlobalNodeList
    
    plot3(axes_handle, x(A), y(A), z(A), 'linestyle','none',...
        'Marker','o',...
        'Color',color,...
        'MarkerFaceColor',color,...
        'MarkerEdgeColor',color);    
end